[storage]
root_dir = "/opt/records"
max_disk_bytes = 536870912000  # 500GB
segment_time_sec = 300         # 5 минут
segment_target_bytes = 104857600
output_format = "ts"
log_dir = "/var/log/slave-recorder"

[ffmpeg]
rtsp_transport = "tcp"

[[streams]]
name = "cam_entrance"
url = "rtsp://example.com:8554/cam1?profile=main"
bearer_token = "YOUR_TOKEN_HERE"

[[streams]]
name = "cam_warehouse"
url = "rtsp://example.com:8554/cam2"

